version: '3.4'

services:
  tor-ip-changer:
    container_name: tor-ip-changer
    image: seevik2580/tor-ip-changer
    privileged: true
    environment:
      - DISPLAY=${DISPLAY:-:0.0}
    network_mode: "host"
    cap_add:
      - ALL
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "9050:9050"
      - "14999:14999"
    command: "ipchanger -d"
